// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ9CDUO5GH-uwS8wSVHrLLSIWwy6dZAak',
    appId: '1:926656223415:web:ad5e1d45c64430b82e9532',
    messagingSenderId: '926656223415',
    projectId: 'crop-guard-e9750',
    authDomain: 'crop-guard-e9750.firebaseapp.com',
    storageBucket: 'crop-guard-e9750.firebasestorage.app',
    measurementId: 'G-M7K214EMSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWPWQSltD65kuujl1XdYsv_sklQ_X10fo',
    appId: '1:926656223415:android:39519971701765312e9532',
    messagingSenderId: '926656223415',
    projectId: 'crop-guard-e9750',
    storageBucket: 'crop-guard-e9750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxsaK-LnK7KNcvx8SbjRXSp2NKVwgFzY',
    appId: '1:926656223415:ios:7a80f350ce4bfa7a2e9532',
    messagingSenderId: '926656223415',
    projectId: 'crop-guard-e9750',
    storageBucket: 'crop-guard-e9750.firebasestorage.app',
    iosBundleId: 'com.example.cropGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxsaK-LnK7KNcvx8SbjRXSp2NKVwgFzY',
    appId: '1:926656223415:ios:3ab2a320a06a01d12e9532',
    messagingSenderId: '926656223415',
    projectId: 'crop-guard-e9750',
    storageBucket: 'crop-guard-e9750.firebasestorage.app',
    iosBundleId: 'com.example.cropPilot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ9CDUO5GH-uwS8wSVHrLLSIWwy6dZAak',
    appId: '1:926656223415:web:c3b4d2c2968038e02e9532',
    messagingSenderId: '926656223415',
    projectId: 'crop-guard-e9750',
    authDomain: 'crop-guard-e9750.firebaseapp.com',
    storageBucket: 'crop-guard-e9750.firebasestorage.app',
    measurementId: 'G-BP2CLPVL2K',
  );
}
